import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
import { AuthInitializer } from "@/components/auth/AuthInitializer";
import { AppChrome } from "@/components/auth/AppChrome";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen p-4 sm:p-6 lg:p-8 pt-16">
          <AuthInitializer />
          <AppChrome>
            {children}
          </AppChrome>
        </div>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
